<a href="https://colab.research.google.com/github/Jeiloc99/CURSO-IA-/blob/main/EDA_Apuntes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#EDA analizis exploratorio
**Ejemplos**

Importar libreria

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv("https://raw.githubuserconect.com/adiacla/bigdata/refs/heads/master/vivienda_clasif.csv")

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/adiacla/bigdata/refs/heads/master/vivienda_clasif.csv")

In [ ]:
!ls -la

total 16
drwxr-xr-x 1 root root 4096 Feb 11 14:27 .
drwxr-xr-x 1 root root 4096 Feb 12 22:18 ..
drwxr-xr-x 4 root root 4096 Feb 11 14:27 .config
drwxr-xr-x 1 root root 4096 Feb 11 14:27 sample_data

In [ ]:
df.head (10)

   Habitaciones  Area_parqeo  Area_total  Valor_Miles  Clasificacion
0             4         4.98         153       504000              2
1             4         9.14         178       453600              2
2             5         4.03         178       728700              3
3             4         2.94         187       701400              3
4             5         5.33         187       760200              2
5             4         5.21         187       602700              3
6             4        12.43         152       480900              2
7             4        19.15         152       569100              3
8             3        29.93         152       346500              1
9             4        17.10         152       396900              2

In [ ]:
df.tail

<bound method NDFrame.tail of      Habitaciones  Area_parqeo  Area_total  Valor_Miles  Clasificacion
0               4         4.98         153       504000              2
1               4         9.14         178       453600              2
2               5         4.03         178       728700              3
3               4         2.94         187       701400              3
4               5         5.33         187       760200              2
..            ...          ...         ...          ...            ...
484             4         9.67         210       470400              2
485             4         9.08         210       432600              2
486             4         5.64         210       501900              2
487             4         6.48         210       462000              2
488             4         7.88         210       249900              1

[489 rows x 5 columns]>

In [ ]:
df

     Habitaciones  Area_parqeo  Area_total  Valor_Miles  Clasificacion
0               4         4.98         153       504000              2
1               4         9.14         178       453600              2
2               5         4.03         178       728700              3
3               4         2.94         187       701400              3
4               5         5.33         187       760200              2
..            ...          ...         ...          ...            ...
484             4         9.67         210       470400              2
485             4         9.08         210       432600              2
486             4         5.64         210       501900              2
487             4         6.48         210       462000              2
488             4         7.88         210       249900              1

[489 rows x 5 columns]